#!/bin/bash

# A skeletal script for setting up the necessary MYSQL databases.
# Set the following environment variable before using it.
# Also edit config/database.yml and put the same password there.

DATABASE_PASSWORD="not set"

#
#  These next three probably don't need changing, but you might want to.
#
DATABASE_PREFIX="scheduler"
DATABASE_USER="scheduler"
CLIENT_HOST="localhost"

if [ "$DATABASE_PREFIX" == "not set" ]; then
  echo "Please edit this script first and set a suitable prefix"
  echo "for your database names."
  exit 1
fi

if [ "$DATABASE_PASSWORD" == "not set" ]; then
  echo "Please edit this script first and set a password which"
  echo "your client programs will use.  (*Not* the admin password"
  echo "for the database engine)."
  exit 1
fi

mysql -u root << EOF
CREATE DATABASE ${DATABASE_PREFIX}_development CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE ${DATABASE_PREFIX}_production CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE ${DATABASE_PREFIX}_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER ${DATABASE_USER} IDENTIFIED BY '${DATABASE_PASSWORD}';

GRANT ALL PRIVILEGES ON ${DATABASE_PREFIX}_development.* TO ${DATABASE_USER};
GRANT ALL PRIVILEGES ON ${DATABASE_PREFIX}_production.* TO ${DATABASE_USER};
GRANT ALL PRIVILEGES ON ${DATABASE_PREFIX}_test.* TO ${DATABASE_USER};

FLUSH PRIVILEGES;

EXIT
EOF
