Date::DATE_FORMATS[:dmy] = "%d/%m/%Y"
Date::DATE_FORMATS[:default] = "%d/%m/%Y"
Time::DATE_FORMATS[:dmy] = "%d/%m/%Y"
Time::DATE_FORMATS[:hmdmy] = "%H:%M %d/%m/%Y"
Time::DATE_FORMATS[:hmsdmy] = "%H:%M:%S %d/%m/%Y"
Time::DATE_FORMATS[:hhmm] = "%H:%M"
Time::DATE_FORMATS[:hm] = "%H%M"
