#!/bin/bash
. /etc/profile
#
#  Are we on development or live?
#
. ~/etc/whichsystem
#
#  And make sure we're using the right ruby.
#
. ~/.rvm/environments/scheduler
#
cd $SCHEDULER_DIR
lib/import/misimport.rb --check --quiet
