#!/bin/bash
. /etc/profile
. ~/etc/whichsystem
cd $SCHEDULER_DIR
~/.rvm/wrappers/scheduler/rake daily:check_approvals
~/.rvm/wrappers/scheduler/rake daily:adjust_currency_flags
~/.rvm/wrappers/scheduler/rake daily:report_loadings
~/.rvm/wrappers/scheduler/rake daily:prompt_for_forms
~/.rvm/wrappers/scheduler/rake daily:prompt_for_reconfirmation
~/.rvm/wrappers/scheduler/rake daily:prompt_for_staff
