#!/bin/bash
. /etc/profile
#
#  The next file contains confidential authentication information,
#  specifically the apikey for the API and the password for direct
#  d/b access.  In a separate file so we can commit this file
#  to version control.
#
. ~/etc/isauth
#
#  Are we on development or live?  Where are our directories etc?
#
. ~/etc/whichsystem
#
#  And make sure we're using the right ruby.
#
. ~/.rvm/environments/scheduler
#
#
#  Now some checks to make sure that at least the part of the
#  environment which we need has been set.
#
if [ "a$SCHEDULER_DIR" == "a" ]; then
  echo "SCHEDULER_DIR environment variable needs to be set."
  exit 1
fi
if [ ! -d $SCHEDULER_DIR/import/isams ]; then
  echo "$SCHEDULER_DIR/import/isams does not seem to be a directory."
  exit 2
fi

cd $SCHEDULER_DIR/import/isams
rm -f Incoming/*

#
#  Are we making use of data from the iSAMS API - either fetching it
#  now or an old one which we have to hand?
#
if [ "$USE_ISAMS_API" = true ]; then
  if [ -f PreFetched/data.xml ]; then
    echo "Using pre-fetched data.xml"
    cp PreFetched/data.xml Incoming
  else
    if [ "a$ISAMS_API_URL" == "a" ]; then
      echo "ISAMS_API_URL environment variable needs to be set."
      exit 3
    fi
    if [ "a$APIKEY" == "a" ]; then
      echo "APIKEY environment variable needs to be set."
      exit 4
    fi
    curl --silent $ISAMS_API_URL?apikey=$APIKEY --output Incoming/data.xml
    if [ $? -ne 0 ]; then
      echo "Failed to fetch iSAMS API data."
      exit 5
    fi
  fi
else
  echo "Not using iSAMS API data."
fi

#
#  And are we using additional data retrieved directly from the iSAMS
#  database - again either doing it now or having done it earlier?
#
if [ "$USE_ISAMS_DB" = true ]; then
  if [ -f PreFetched/TblActivityManagerEvent.csv ]; then
    echo "Using pre-fetched csv files."
    cp PreFetched/*.csv Incoming
  else
    $SCHEDULER_DIR/utils/fetchisdata/extractor.rb --target Incoming --extract
    if [ $? -ne 0 ]; then
      echo "Failed to fetch date from iSAMS database."
      exit 6
    fi
  fi
else
  echo "Not using iSAMS table data."
fi

#
#  We now appear to have a set of data files.  Move them to Current
#  and then archive them.
#
rm -f Current/*
mv Incoming/* Current
TARGET_DIR="Archive/`date +%Y/%m/%d`"
mkdir -p $TARGET_DIR
cp Current/* $TARGET_DIR
if [ "$USE_ISAMS_API" = true ]; then
  bzip2 -f $TARGET_DIR/*.xml
fi
if [ "$USE_ISAMS_DB" = true ]; then
  bzip2 -f $TARGET_DIR/*.csv
fi

#
#  And now invoke the import utility to bring the new data into Scheduler.
#
$SCHEDULER_DIR/lib/import/misimport.rb --quiet --email | tee import.log
cp import.log $TARGET_DIR
bzip2 -f $TARGET_DIR/import.log

#
#  Feed to markbook if configured.
#
if [ "$FEED_MARKBOOK" == "true" ]; then
  rsync ../ForMarkbook/*.yml markbook:FromScheduler
fi
