#!/bin/bash
. /etc/profile
. ~/etc/sbauth
cd ~/Work/Coding/scheduler
#echo $PATH
utils/fetchsbdata.rb
RAILS_ENV=production
export RAILS_ENV
~/.rvm/wrappers/scheduler/ruby lib/import/importsb.rb --email
cd import
/bin/tar cf - *.csv | gzip -9c >archive/`date +%Y%m%d`.tar.gz
scp *.yml nimbus.sinodun.org.uk:Work/Coding/markbooklive/import/data/2014
