#!/bin/bash
. /etc/profile
#
#  The next file contains confidential authentication information,
#  specifically the apikey for the API and the password for direct
#  d/b access.  In a separate file so we can commit this file
#  to version control.
#
. ~/etc/isauth
#
#  Are we on development or live?
#
. ~/etc/whichsystem
#
#  And make sure we're using the right ruby.
#
. ~/.rvm/environments/scheduler
#
cd ~/Work/Coding/scheduler/import/isams
rm -f Incoming/*
if [ "$USE_ISAMS_API" = true ]; then
  if [ -f PreFetched/data.xml ]; then
    echo "Using pre-fetched data.xml"
    cp PreFetched/data.xml Incoming
  else
    curl --silent https://abingdon.isams.co.uk:443/api/batch/1.0/xml.ashx?apikey=$APIKEY --output Incoming/data.xml
  fi
else
  echo "Not using iSAMS API data."
fi
if [ $? -eq 0 ]; then
  if [ "$USE_ISAMS_DB" = true ]; then
    if [ -f PreFetched/TblActivityManagerEvent.csv ]; then
      echo "Using pre-fetched csv files."
      cp PreFetched/*.csv Incoming
    else
      ../../utils/fetchisdata/extractor.rb --target Incoming --extract
    fi
  else
    echo "Not using iSAMS table data."
  fi
  if [ $? -eq 0 ]; then
    #
    #  We now appear to have a set of data files.  Move them to Current
    #  and then archive them.
    #
    rm -f Current/*
    mv Incoming/* Current
    TARGET_DIR="Archive/`date +%Y/%m/%d`"
    mkdir -p $TARGET_DIR
    cp Current/* $TARGET_DIR
    if [ "$USE_ISAMS_API" = true ]; then
      bzip2 -f $TARGET_DIR/*.xml
    fi
    if [ "$USE_ISAMS_DB" = true ]; then
      bzip2 -f $TARGET_DIR/*.csv
    fi
    #
    #  And now invoke the import utility to bring the new data into Scheduler.
    #
    ../../lib/import/misimport.rb --quiet --email | tee import.log
    cp import.log $TARGET_DIR
    bzip2 -f $TARGET_DIR/import.log
    #
    #  Feed to markbook if configured.
    #
    if [ "$FEED_MARKBOOK" == "true" ]; then
      rsync ../ForMarkbook/*.yml markbook:FromScheduler
    fi
  else
    echo "Failed to fetch data from iSAMS d/b."
  fi
else
  echo "Failed to fetch data from iSAMS API."
fi
