#!/bin/bash
#
#  You really don't want to run this script by mistakely, so by default
#  it refuses to run at all.  Delete the next three lines if you really
#  want to use it.  It's intended for use merely on a demo system.
#
echo "Do you really want to purge your entire database?"
echo "If so, then edit this script and remove these lines."
exit 1
#

. /etc/profile
#
#  Are we on development or live?
#
. ~/etc/whichsystem
#
#  And make sure we're using the right ruby.
#
. ~/.rvm/environments/scheduler
#
#  Make sure SCHEDULER_DIR is set
#
if [ "a$SCHEDULER_DIR" == "a" ]; then
  echo "SCHEDULER_DIR environment variable needs to be set."
  exit 1
fi
if [ -d $SCHEDULER_DIR ]; then
  cd $SCHEDULER_DIR
  rake db:schema:load >/dev/null
  rm -rf UserFiles/*
  mkdir UserFiles/Test
  cat << EOF >UserFiles/Test/.gitignore
*
!.gitignore
EOF
  #
  #  Erase only dynamically created thumbnails.  They all have exactly
  #  12 characters in the first part of the filename.
  #
  rm -rf public/thumbnails/????????????.png
  rake db:seed
  ./lib/clashes/clashcheck.rb --weeks 1 --start `./lib/clashes/sundate.rb`
else
  echo "$SCHEDULER_DIR does not seem to be a directory."
  exit 2
fi
